services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
        - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
        - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    container_name: discord-scrape-bot-api
    ports:
      - "8000:8000"
    volumes:
      - ./api/db.sqlite3:/app/db.sqlite3
    env_file:
      - ./api/.env
    user: "8877:8877"
    restart: always
  discord-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: discord-bot
    volumes:
     - ./bot/previous_boot.json:/bot/previous_boot.json
    env_file:
      - bot/.env
    depends_on:
      - api
    restart: always