# Generated by Django 5.1.4 on 2024-12-31 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Embed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("title", models.TextField(blank=True, null=True)),
                ("color", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("content", models.TextField(blank=True)),
                ("channel_id", models.BigIntegerField()),
                ("channel_name", models.CharField(max_length=100)),
                ("author_id", models.BigIntegerField()),
                ("author_name", models.CharField(max_length=100)),
                ("author_discriminator", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField()),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sticker",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EmbedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("value", models.TextField(blank=True)),
                ("inline", models.BooleanField(default=False)),
                (
                    "embed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="logger.embed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmbedFooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("icon_url", models.TextField(blank=True)),
                ("proxy_icon_url", models.TextField(blank=True)),
                (
                    "embed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer",
                        to="logger.embed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmbedThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(blank=True)),
                ("proxy_url", models.TextField(blank=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("flags", models.IntegerField(default=0)),
                (
                    "embed",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="logger.embed",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="embed",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeds",
                to="logger.message",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("url", models.TextField(blank=True)),
                ("filename", models.TextField()),
                ("size", models.IntegerField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="logger.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageContentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_history",
                        to="logger.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageEmbedHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embed_data", models.JSONField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embed_history",
                        to="logger.message",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="stickers",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="logger.sticker"
            ),
        ),
    ]
