# Generated by Django 5.1.4 on 2024-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedfooter',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='embedfooter',
            name='proxy_icon_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='embedthumbnail',
            name='proxy_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='embedthumbnail',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
