# Generated by Django 5.1.4 on 2024-12-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_embedfooter_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedfield',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
