# Generated by Django 5.1.4 on 2025-01-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0002_embed_description_alter_embed_color_alter_embed_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
