# Generated by Django 5.1.4 on 2024-12-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_remove_sticker_message_message_stickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedfooter',
            name='proxy_icon_url',
        ),
        migrations.RemoveField(
            model_name='embedthumbnail',
            name='proxy_url',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='embedfield',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='embedfooter',
            name='icon_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='embedfooter',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='embedthumbnail',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='url',
            field=models.TextField(),
        ),
    ]
