# Generated by Django 5.1.4 on 2024-12-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_embedfooter_proxy_icon_url_embedthumbnail_proxy_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='embedfield',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
