# Generated by Django 5.1.4 on 2024-12-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0007_alter_embed_title_alter_embedfield_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='original_content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EmbedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.TextField(blank=True)),
                ('color', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('embed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='logger.embed')),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='logger.message')),
            ],
        ),
    ]
