# Generated by Django 5.1.4 on 2024-12-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_message_is_edited_message_original_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedhistory',
            name='message_history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='embed_histories', to='logger.messagehistory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='original_embeds',
            field=models.ManyToManyField(blank=True, related_name='original_embeds', to='logger.embed'),
        ),
    ]
