# Generated by Django 5.1.4 on 2024-12-30 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0009_embedhistory_message_history_message_original_embeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_embeds',
        ),
        migrations.DeleteModel(
            name='EmbedHistory',
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
