# Generated by Django 5.1.4 on 2024-12-30 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_messagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_history', to='logger.message')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
