# Generated by Django 5.1.4 on 2024-12-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_messagecontenthistory_delete_messagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEmbedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_data', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_history', to='logger.message')),
            ],
        ),
    ]
